# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a4e0cf2c4cf42b40aec87401f86e603112f6c35fbff17178ae12c69efbd9a2bc0339d65a9a0edef6aa6072a7a7ea000ee1efdf688d836ffb3997675ae582b7a

test:
  secret_key_base: 827c2920ea9e6c91eae0b44e50feda1f51df8f7dd3d6dfa08a76cace471b0ae9010f0a74e7b8daca53156a31852b484f4cc7a594eaf08aca4dbfdda5f5295ef3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
